### ISSUE TITLE
Syntax highlighting breaks on closing parenthesis in comment 

### ISSUE THREAD

**Issue by alimbada** [MarkusAmshove/vscode-natural#47]
Found another issue similar to #45 

Sample code as generated by NaturalONE:

```
/*( imported data fields from Data Definition Module
01 X VIEW OF Y
  02 FOO (A10)
/*) imported data fields from Data Definition Module
```
This one is a very minor issue as the syntax highlighting is only broken on the last line with `/*)...` and does not affect the rest of the files as it did in #45

**Comment by MarkusAmshove** [comment]
That is a tricky one, because `/*)`  is also used in type definitions for arrays, e.g. `(A1/*)`, because why not :)

I've added a workaround that should highlight this case, but only if the comment is started at the start of line, which your case looks like.

More ambiguous things will one day be solved when the underlying language server does semantic highlighting.
